language: node_js

node_js:
- node

branches:
  except:
  - /^v?\d+\.\d+\.\d+$/

script:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=0.0.$TRAVIS_BUILD_NUMBER
- npm version $GIT_TAG --force
- npm run eslint

before_deploy:
- git tag $GIT_TAG -a -m $GIT_TAG
- git push -q https://$GITHUB_TOKEN@github.com/andrewmolyuk/mongo-leader --tags

deploy:
  skip_cleanup: true
  provider: npm
  email: andrew.molyuk@gmail.com
  api_key: $NPM_APIKEY
  tag: next

env:
  global:
  - secure: Vbn9CkM0bpz4A9/yhZsgwPTa36tqe0BSflHOAJqn1mOCW6IweWaJoRKke0t6E3GYo9Ew9FG67IRxJYVb43ePzODzXao+dQNx4JGEbqFRoZMBnzUun1Zf/2C2hJdKOYanOxeHSZksxYo50wmhApUbjVbxaz/p+v4G8kQVXP0Iu2jkV6cVyMjJTEHVdxo0m0/E76xTfvxf0ylOfQNyB06sgEFXjjO6yh3CrO5z0CfWZ7KxVj4qbroW8GSyljZoRklI1wIK0m8JFXhvYxQgbfD3GDku+hR7WVRnEKTfCz/EBCvcaLvHkxONyW1FDpe51aI2FyewviIXYuYY03uXp1TQBd9QkwDZ6dHDhRXkiM/9tGSPMedEwfAAJDvaygHVEhpnl/wqejpyG3ZcwTsVeNDGwwMAm4sEx676UfNnsDh2slwDcSeXtpr1VOFMn+iUeSjKeDiNiMpovaO+UDKT46gANDeODhVluHjvP74dHuifG54oOE757v2WUBaTAZfZAtEY96M2qAOcgkQ+5Dw3Gq5pMsHLiz2yoo9bYAtGVyB96nS/CpKA2wfBjboNZUsHWhtddZuvj0iGxGKNgH33FLzzLQHMMzmnsmcVEAz5ajByNw3Bw+RO96aTzMDTOoZvPUgH9TR1m8eZKVuSxsWvjdPegYp/jmItEMfb+cD/uv+q6IM=
  - secure: itKCRIDgavnzv6zoQ8g+AcJNAtENfytNyLgMoDW2aQnAwdSwQJUPyAO1hHHFsvAOaFDHnnL92GRvQccYcVZan7l5uXftP+ToXQYxlk8osTaKHa7S4kgvbLFd6U5sIxFnDpI/mCUQPoI3Z/NrSBwVWOneAatcyxS0UcVNNXrB+cJ+SrQkWYiVPwtbNs7y6aPfgzQNJGaes7pX9wUENV4AGk9+AJ9Oeqn4+1rmmeXLORf76E9cdVxBuxs5bxDb18zykUi+MRs2m9EHiA1fcYi/RPMWA81a5UXMEetCZfl0+phn1Tu4ek3Syc01IQIBoqyEGsioA12gtHGGNaM7gwzQsPLSoJ1WIhkf4xa/pDK5JZeMtPEZ9U6g68PFXnCiO5/2SkTYc8noUYdShiacrn8j6TmcxcinxS5ZagZA4AgyzkLhOl/15Mgo6n4QgIFrVm2TSBCo6aTKgqXrQlWAJwIQ6/SsATYFL9pWDCuq2PzcR77icXvon8F5b26coRoNWeEKeIbfEfFnN48UI0MlqTXjKsZNZgiIO+ImG7JKrcMmBU7S0T28vsKBfvND/8EC1d7DwKeeEZKUFiZnoBbHFBjK0z9AGaRdJFRsGB4JHKtnXH0yK58anZ3USh4aUDS6GBdWRq6oO69Gi3yls50u1t3OTlAfdxebQbOA9JbjdS5tPoo=