language: node_js
node_js:
- node
branches:
  only:
  - master
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=1.0.$TRAVIS_BUILD_NUMBER
- npm version $GIT_TAG --force
- npm run eslint
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
before_deploy:
- git tag $GIT_TAG -a -m $GIT_TAG
- git push https://$GITHUB_TOKEN@github.com/andrewmolyuk/mongo-leader --tags
deploy:
  provider: npm
  email: andrew.molyuk@gmail.com
  api_key: "$NPM_TOKEN"
env:
  global:
  - secure: Fipae1S28vS5jAR+Oetch5+4D1SKmGtqsCjpwc3kHPi3GKuJ+zQ0Vm2i23doXZO19Ledc44J9fib3t5FefW2fXVvBr84WwhwePve/IBbTT3doZ5Dj1eM8JfSEbhawxcRGbgI73gxYfPDGBfs4L571cAceaubRXHbr5RcpLA5YRfUXqWVnMjhUOy8mP2PfNDkEf38tL8HiUNBUjX1er4+/X94/FGnO9a1C6VqAcrvo/fKiEAG9BfhcAE3FzH873BLt3JEMNlkKKYT7MxZHh9aeW9Lu0nFnFLcvF8CS9sIhEFLl8seDxLqwfvcf2Q1vJDkN2fIUwZ4sFuKbtWQFCXnX3sbxKmjg3UB4M/tTI2qwHBRKbGYOU36YZ2eT7relZVdRKSmBzs9gDOSruj/69u/YHTJpZ9SwzsQHFHlQ+7W7jkKiXELqVGM6wmND7jLZ3HPm0A/vN2xY9R+/VorUI3Fq8AjkD8EF/QPGunsWdAjCpXY69CNWWZhsjGeR4MytuajYGAgCnQzVz2J8ZBRL2NNEIyILFAkCj+VjkjjcjQr+h0Ckce1vOTomYH96uImEjss7pVCngL3NEipwt1yexeA1m5i2Ue6MjqQgc7sX3KEYsa6JXGgpgQ8UZIO5UsGa8c3zOzZtTY2Zn79x2zUPCA+dEgd9K80Fchw7VWTq+lcIWU=
  - secure: C/2f/UG351qjzFA/23d1F/aqp+NKyBXUrkv7LtotCNhWfimKrBKNbK701fHOrbPKfTZdJXQwcLw8Rnele6fyVtTQrsArQr6jiNFUStiOXzPG9IN2lMUh9f+9/S8AhQV2RYeHplgbFnWdMuwQzt9rnSfMRKrHliVjcBi0yLedbb8Cb3dIA3QwmyTQ+Mk2fLV3IUz7KE4G8satp2LN6SHbEu4Zm+KmfegH6ocRntEFFhcV8oybZQghePtAasvum2KRjWLXVyqFZ8overh47cvLD4aaFadoahuMzY/ERjSQnEKdfEl0oBURsis9cn1UlYU0IPHMK0PyLI5IcdP4O+LYklIERSe3v1dJP0FCUg7gG6QoIecZQx5UfbQqZYXDMV8tcbBnvpDAe5CuXtHIsLVCtaCQC2v56bDY0wpjgS7SPWllnqZRQAMCNcPsSq6C6d4Kr9ki+0pLaEPVrPe3geuxPqYd/tt3893Xb32kNBaCDOEUfai/8u+LunSIpr/vPrIYAtyKsFT+SdpQtA5uM+jW/Ayp8R2vy9X9QW93rqzpkrdpZYSI8A+tSDbSIX0TI4yrIeCIvm1kS82QtHh9Bs5+VScjPIwZRGnwosT7Ny7ZhluncTWzP9XeQ2JdYaQZAOSY5Ii1G5FCsNGuzqYjQvX6zXCIznNHCSszFb6YqllX1AU=
